# Generated by Django 4.2.2 on 2023-06-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulturistika', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zavodnik',
            name='trener',
            field=models.ManyToManyField(to='kulturistika.trener'),
        ),
    ]
